spring.application.name=academy
server.port=${PORT:9001}

DB_URL=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/academyDB?sslMode=VERIFY_IDENTITY
DB_USERNAME=x5EFVVWUw377s7h.root
DB_PASSWORD=evPhEhR42cBFtTZV
P_KEY=7b421a0361920c2ee8b55cdc39781b27

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

jwt.secret=7b421a0361920c2ee8b55cdc39781b27
jwt.expiration-ms=3600000